config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get '/books' => 'books#index'
  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :readers, through: :ownerships
  has_many :ownerships

  default_scope {order("title")}
end

app/models/library.rb
class Library < ActiveRecord::Base
  belongs_to :reader
  belongs_to :book
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :reader
  belongs_to :book

  default_scope {order("status")}
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  has_many :books, through: :ownerships
  has_many :ownerships

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def safe_params?(query)
    query =~ /destroy|delete|\bupdate\b|\bcreate\b|build/ ? false : true
  end

  def fetch_model_records
    if @records.class.to_s =~ /Book/
      fetch_book_records
      @book_status, @reader_status, @ownership_status = true, false, false
    elsif @records.class.to_s =~ /Reader/
      fetch_reader_records
      @book_status, @reader_status, @ownership_status = false, true, false
    elsif @records.class.to_s =~ /Ownership/
      fetch_ownership_records
      @book_status, @reader_status, @ownership_status = false, false, true
    else
      flash[:error] = "You found a unicorn of an error! Congrats, I guess."
      redirect_to root_path
    end
  end

  def fetch_book_records
    if @records.is_a?(Book)
      @books, @readers, @ownership_statuses = [@records], @records.readers, @records.ownerships.select(:status).distinct
    else
      readers, ownerships = [], []
      begin
        @records.each do |b|
          readers += b.readers
          ownerships += b.ownerships
        end
      rescue ActiveRecord::StatementInvalid => e
        flash[:error] = "Bad query. Baaaad query."
        redirect_to root_path
      else
        @books = @records
        @readers = readers.uniq
        @ownership_statuses = ownerships.uniq {|o| o.status }
      end
    end
  end

  def fetch_reader_records
    if @records.is_a?(Reader)
      @books, @readers, @ownership_statuses = @records.books, [@records], @records.ownerships.select(:status).distinct
    else
      books, ownerships = [], []
      begin
        @records.each do |r|
          books += r.books
          ownerships += r.ownerships
        end
      rescue ActiveRecord::StatementInvalid => e
        flash[:error] = "Bad query. Baaaad query."
        redirect_to root_path
      else
        @books = books.uniq
        @readers = @records
        @ownership_statuses = ownerships.uniq {|o| o.status }
      end
    end
  end

  def fetch_ownership_records
    if @records.is_a?(Ownership)
      @books, @readers, @ownership_statuses = @records.book, @records.reader, [@records]
    else
      books, readers = [], []
      begin
        @records.each do |o|
          books += [o.book]
          readers += [o.reader]
        end
      rescue ActiveRecord::StatementInvalid => e
        flash[:error] = "Bad query. Baaaad query."
        redirect_to root_path
      else
        @books = books.uniq
        @readers = readers.uniq
        @ownership_statuses = @records.select(:status).distinct
      end
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:query] && !params[:query].empty? && safe_params?(params[:query])
      @query = params[:query]
      begin
        @records = eval(@query)
      rescue NoMethodError => e
        flash[:error] = "Bad method. Baaaad method."
        redirect_to root_path
      rescue NameError => e
        flash[:error] = "Are you sure you spelled the model name right?"
        redirect_to root_path
      rescue SyntaxError => e
        flash[:error] = "Syntactical errors ahoy!"
        redirect_to root_path
      rescue
        flash[:error] = "What happened? We're investigating!"
        redirect_to root_path
      else
        fetch_model_records
      end
    else
      @books, @book_status = Book.all, true
      @readers, @reader_status = Reader.all, true
      @ownership_statuses, @ownership_status = Ownership.select(:status).distinct, true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def model_class(model_status)
    if model_status
      'primary_record'
    else
      'secondary_record'
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= content_tag :tr, id: "book-#{book.id}" do %>
  
    <td><%= book.title %></td>
    
    <td><%= book.author %></td>
<% end %>

app/views/books/_ownership.html.erb
<div>
<tr>
    <td><%= ownership.status %></td>
</tr>
</div>

app/views/books/_reader.html.erb
<%= content_tag :tr, id: "reader-#{reader.id}" do %>
  <td><%= reader.name %></td>
  <td><%= reader.age %></td>
  <td><%= reader.gender %></td>
<% end %>

app/views/books/index.html.erb
<div class="header-text"><span class="reader">Readers</span> have many <span class="book">books</span> through <span class="ownership">ownerships</span>.</div>

<div id="circles">
  <div class="reader-model reader"></div>
  <div class="book-model book"></div>
  <div class="ownership-model ownership"><span></span></div>
</div>
<br/>

<div class="row">
  <div class="col-md-7 center-block">
  <%= form_tag books_path, method: 'get', id: 'database-search' do %>
    <p>
      <div class="input-group">
        <%= text_field_tag :query, params[:query], class: 'form-control' %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: 'btn btn-default', :name => nil %>
        </span>
      </div>
      
    </p>
  <% end %>
  </div>
</div>

<div class="col-md-5">
  <div>books</div>
  <%= content_tag :table, class: "table #{model_class(@book_status)}" do %>
    <tr>
      <th>title</td>
      <th>author</td>
    </tr>
      <%= render partial: 'book', collection: @books %>
  <% end %>
</div>

<div class="col-md-3">
  <div>ownerships</div>
  <%= content_tag :table, class: "table #{model_class(@ownership_status)}" do %>
    <tr>
      <th>status</th>
    </tr>
    <%= render partial: 'ownership', collection: @ownership_statuses %>
  <% end %>
</div>

<div class="col-md-4">
  <div>readers</div>
  <%= content_tag :table, class: "table #{model_class(@reader_status)}" do %>
    <tr>
      <th>name</th>
      <th>age</th>
      <th>gender</th>
    </tr>
    <%= render partial: 'reader', collection: @readers.sort_by {|v| v.name[/\s(\w+)/,1] } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Databases</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700|Raleway:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>

  <div class="container">
    <br/>
    <div id="flash-container">
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= flash[:notice] unless flash[:notice].blank? %></div>
      <% elsif flash[:error] %>
        <div class="alert alert-warning alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= flash[:error] unless flash[:error].blank? %></div><br/><br/><br/>
      <% end %>
    </div>
    
    <%= yield %>
  </div>
</body>
</html>